spring.application.name=incident-service
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/incident_db

spring.cloud.aws.credentials.access-key=fake-access-key
spring.cloud.aws.credentials.secret-key=fake-secret-key
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.s3.path-style-access-enabled=true